!> Tester for the cuckoo hash map implementation
subroutine test_cuckooroost
   use assertion
   use xtb_mctc_namegen
   use xtb_type_abstractdata
   use xtb_type_cuckooroost
   implicit none

   type(TCuckooSkein) :: skein

   type(TValue), pointer :: view

   call init(skein, 10)
   call assert_eq(len(skein), 0)

   call skein%get("tight-binding", view)
   call assert(.not.associated(view))

   call skein%insert("tight-binding", view)
   call assert(associated(view))
   call assert_eq(len(skein), 1)

   call skein%insert("semi-empirics", view)
   call skein%insert("semi-empirics", view)
   call skein%insert("quantum-mechanics", view)
   call assert_eq(len(skein), 3)

   call skein%drop("tight-binding")
   call assert_eq(len(skein), 2)

   call skein%insert("talkative-backs", view)
   call skein%insert("thick-bounces", view)
   call skein%insert("tubby-broadcast", view)
   call skein%insert("these-bump", view)
   call skein%insert("tricky-broadcast", view)
   call skein%insert("thick-brush", view)
   call skein%insert("tart-brushes", view)
   call skein%insert("tragic-box", view)
   call skein%insert("thankful-bail", view)
   call skein%insert("trustworthy-balloon", view)
   call skein%insert("tame-balances", view)
   call skein%insert("tight-bumps", view)
   call skein%insert("tangible-bump", view)
   call skein%insert("tart-bother", view)
   call skein%insert("trivial-balloons", view)
   call skein%insert("twin-break", view)
   call skein%insert("tall-bandage", view)
   call skein%insert("twin-boxes", view)
   call skein%insert("tense-bounce", view)
   call skein%insert("thunderous-blast", view)
   call skein%insert("trivial-backs", view)
   call skein%insert("twin-board", view)
   call skein%insert("tremendous-benefits", view)
   call skein%insert("trained-breaks", view)
   call skein%insert("thorny-bank", view)
   call skein%insert("traumatic-bounces", view)
   call skein%insert("traumatic-bank", view)
   call skein%insert("thankful-bargain", view)

   call skein%get("tight-binding", view)
   call assert(.not.associated(view))
   call skein%get("semi-empirics", view)
   call assert(associated(view))
   call skein%get("quantum-mechanics", view)
   call assert(associated(view))
   call skein%get("talkative-backs", view)
   call assert(associated(view))
   call skein%get("thick-bounces", view)
   call assert(associated(view))
   call skein%get("tubby-broadcast", view)
   call assert(associated(view))
   call skein%get("these-bump", view)
   call assert(associated(view))
   call skein%get("tricky-broadcast", view)
   call assert(associated(view))
   call skein%get("thick-brush", view)
   call assert(associated(view))
   call skein%get("tart-brushes", view)
   call assert(associated(view))
   call skein%get("tragic-box", view)
   call assert(associated(view))
   call skein%get("thankful-bail", view)
   call assert(associated(view))
   call skein%get("trustworthy-balloon", view)
   call assert(associated(view))
   call skein%get("tame-balances", view)
   call assert(associated(view))
   call skein%get("tight-bumps", view)
   call assert(associated(view))
   call skein%get("tangible-bump", view)
   call assert(associated(view))
   call skein%get("tart-bother", view)
   call assert(associated(view))
   call skein%get("trivial-balloons", view)
   call assert(associated(view))
   call skein%get("twin-break", view)
   call assert(associated(view))
   call skein%get("tall-bandage", view)
   call assert(associated(view))
   call skein%get("twin-boxes", view)
   call assert(associated(view))
   call skein%get("tense-bounce", view)
   call assert(associated(view))
   call skein%get("thunderous-blast", view)
   call assert(associated(view))
   call skein%get("trivial-backs", view)
   call assert(associated(view))
   call skein%get("twin-board", view)
   call assert(associated(view))
   call skein%get("tremendous-benefits", view)
   call assert(associated(view))
   call skein%get("trained-breaks", view)
   call assert(associated(view))
   call skein%get("thorny-bank", view)
   call assert(associated(view))
   call skein%get("traumatic-bounces", view)
   call assert(associated(view))
   call skein%get("traumatic-bank", view)
   call assert(associated(view))
   call skein%get("thankful-bargain", view)
   call assert(associated(view))

   call skein%clear
   call assert_eq(len(skein), 0)

   call terminate(afail)

end subroutine test_cuckooroost
